send the createdBatch in uploadMsg
spotify/confidence-openfeature-provider-java pull request #89
Opened 2024-03-15 12:58 UTC by nicklasl

2024-03-15 16:26 UTC, fabriziodemaria requested changes

2024-03-15 16:26 UTC, fabriziodemaria commented on src/main/java/com/spotify/confidence/eventsender/EventSenderEngineImpl.java
> +          uploadQueue.add(new UploadMsg(UPLOAD_SIG, eventStorage.createBatch()));
If the `UploadPoller` thread is slow for any reason, we might enqueue multiple "UploadMsg"s that will contain (partly) the same batches in it, leading to event duplications. Am I understanding this correctly?

2024-03-19 12:34 UTC, fabriziodemaria commented
I suggest we close this PR, if my comment above is valid

2024-03-19 12:35 UTC, nicklasl commented
agreed! closing.

2024-03-19 12:35 UTC, closed without merging